# Worflow pour IC
name: Yarn CI UI

on: [push]

jobs:
  # Single job
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repository
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Run Yarn Install
        run: |
          cd ui
          yarn install

      # Run jest tests
      - name: Run Tests
        run: |
          cd ui
          yarn test
          BABEL_ENV=e2e yarn e2e:headless

      # Upload vers codecove (Evaluation couverture du code par des tests)
      - name: Upload UI coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./ui/coverage
          name: codecov-ui
          verbose: true
